title: Luka
tagline: My personal webpage.
#email: 
description: >-
  My personal webpage.
baseurl: ""
url: "https://lukam-oss.github.io"

github:
  username: lukam-oss

social:
  name: Luka
  email: 164436043+lukam-oss@users.noreply.github.com
  links:
    - https://github.com/lukam-oss

theme: jekyll-theme-chirpy
lang: en
timezone: America/Toronto
#plugins:
#  - jekyll-feed

avatar: "https://avatars.githubusercontent.com/u/164436043"

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order
  
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true 
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/js/dist
    values:
      swcache: true
    
sass:
  style: compressed

exclude:
  - bin/*
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json